language: node_js

node_js:
  - node

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn
  - mkdir temp
  - tar -czvf temp/app.tar.gz packages/app
  - tar -czvf temp/webapp.tar.gz packages/webapp

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    skip_cleanup: true
    overwrite: true
    file:
      - "temp/app.tar.gz"
      - "temp/webapp.tar.gz"
    on:
      tags: true

  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: website/build
    on:
      tags: true
